# Deploys when push is made from front end folder
# added paths variable on line 9 because this allows you to track changes from just frontend folder
# added the active versions
name: deploy_frontend

on:
    push:
        branches: [ main ]
        paths:
          - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        activeversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name bldstg2 -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        activeversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "ResumeCDN" --name "wbldcldcpaep1" --resource-group "ACGResumeChallenge"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()